const pledges = [
  "I stand with the flame. I’m Fogolised 🔥",
  "No hype, just heat. I’m Fogolised 🔥",
  "My wallet may be cold, but my soul’s on fire. I’m Fogolised 🔥",
  "This chain runs in my digital veins. I’m Fogolised 🔥",
  "I don’t follow trends. I follow the fire. I’m Fogolised 🔥",
  "Where there’s smoke, there’s me. I’m Fogolised 🔥",
  "My commitment is forged in flames. I’m Fogolised 🔥",
  "I walk with the ember of purpose. I’m Fogolised 🔥",
  "On-chain or off — I bring the heat. I’m Fogolised 🔥",
  "This is more than a chain. It's my ecosystem. I’m Fogolised 🔥",
  "Some stake, I pledge. I’m Fogolised 🔥",
  "Together, we light up the block. I’m Fogolised 🔥",
  "I’m not just a user. I’m a believer. I’m Fogolised 🔥",
  "Decentralized? Yes. Disconnected? Never. I’m Fogolised 🔥",
  "This fire’s not fading. I’m in for the long burn. I’m Fogolised 🔥",
  "No FUD, just flames. I’m Fogolised 🔥",
  "Not hype. It’s identity. I’m Fogolised 🔥",
  "I post, pledge, and power the chain. I’m Fogolised 🔥",
  "One fire. One future. One Fogo. I’m Fogolised 🔥",
  "I refresh my page, not my loyalty. I’m Fogolised 🔥",
  "In block we trust, in fire we unite. I’m Fogolised 🔥",
  "I don’t mint promises. I pledge them. I’m Fogolised 🔥",
  "Fueling the fire with every click. I’m Fogolised 🔥",
  "I run on passion. The chain runs on Fogo. I’m Fogolised 🔥",
  "It’s not just a chain. It’s where I belong. I’m Fogolised 🔥",
  "I carry the ember of change. I’m Fogolised 🔥",
  "I breathe decentralized fire. I’m Fogolised 🔥",
  "My loyalty is chain-locked. I’m Fogolised 🔥",
  "Pledged, not pressured. I’m Fogolised 🔥",
  "Fogo is not hype — it’s home. I’m Fogolised 🔥",
  "I don’t join chains. I become them. I’m Fogolised 🔥",
  "Every pledge adds fuel to the fire. I’m Fogolised 🔥",
  "I’m not early. I’m eternal. I’m Fogolised 🔥",
  "The flame chose me. I’m Fogolised 🔥",
  "No chill, just chain. I’m Fogolised 🔥",
  "My address is fire-encoded. I’m Fogolised 🔥",
  "Gasless or not — I stay lit. I’m Fogolised 🔥",
  "Chains don’t bind me, they empower me. I’m Fogolised 🔥",
  "I’m the block that burns the brightest. I’m Fogolised 🔥",
  "My role? Firestarter. I’m Fogolised 🔥",
  "I’m on fire, and it’s not metaphorical. I’m Fogolised 🔥",
  "This isn’t just a pledge. It’s a pact. I’m Fogolised 🔥",
  "Forged by fire, fueled by Fogo. I’m Fogolised 🔥",
  "No testnet, no problem. My loyalty is mainnet-ready. I’m Fogolised 🔥",
  "I don’t need incentives. I need ignition. I’m Fogolised 🔥",
  "If it’s not Fogo, it’s just smoke. I’m Fogolised 🔥",
  "This isn’t an airdrop. It’s a downpour of purpose. I’m Fogolised 🔥",
  "I don’t jump chains. I build them. I’m Fogolised 🔥",
  "With Fogo, I'm home. I’m Fogolised 🔥",
  "I don’t mint for clout. I mint for the cause. I’m Fogolised 🔥",
  "From embers to ecosystem — I grow with Fogo. I’m Fogolised 🔥",
  "Every keystroke is a spark. I’m Fogolised 🔥",
  "I don’t wait for flames. I make them. I’m Fogolised 🔥",
  "This chain is lit — and I’m the reason. I’m Fogolised 🔥",
  "You bring the code, I bring the fire. I’m Fogolised 🔥",
  "No faucet needed. I’m overflowing. I’m Fogolised 🔥",
  "I pledge not because I have to. But because I want to. I’m Fogolised 🔥",
  "Fogo isn't my project. It's my pulse. I’m Fogolised 🔥",
  "Not just Web3. Web🔥. I’m Fogolised 🔥",
  "This community? It’s lava. I’m Fogolised 🔥",
  "I pledged. I stayed. I burned. I’m Fogolised 🔥",
  "Every refresh brings a new flame. I’m Fogolised 🔥",
  "Code runs. I burn. I’m Fogolised 🔥",
  "Call me a pyro — I’m loyal to fire. I’m Fogolised 🔥",
  "Not an early adopter. An eternal one. I’m Fogolised 🔥",
  "This isn't onboarding. It’s ignition. I’m Fogolised 🔥",
  "I speak fluent Fogo. I’m Fogolised 🔥",
  "I vibe with validators. I’m Fogolised 🔥",
  "No roadmap needed when you follow fire. I’m Fogolised 🔥",
  "Proof of Flame. That's my consensus. I’m Fogolised 🔥",
  "I fuel this. Not just follow. I’m Fogolised 🔥",
  "I pledge with purpose, not pressure. I’m Fogolised 🔥",
  "Here since block zero. Staying till forever. I’m Fogolised 🔥",
  "You test tokens. I test loyalty. I’m Fogolised 🔥",
  "More than just gas fees — it's gas flames. I’m Fogolised 🔥",
  "I’m not bullish. I’m blazing. I’m Fogolised 🔥",
  "Proof of community, proof of commitment. I’m Fogolised 🔥",
  "Burned bridges. Built chains. I’m Fogolised 🔥",
  "No gimmicks. Just grit. I’m Fogolised 🔥",
  "I plant my flag in fire. I’m Fogolised 🔥",
  "This isn’t hype — it’s heritage. I’m Fogolised 🔥",
  "Community over coins. I’m Fogolised 🔥",
  "Let the doubters doubt. I burn bright. I’m Fogolised 🔥",
  "I’m not in for the drop. I’m in for the rise. I’m Fogolised 🔥",
  "Chain or no chain, I stand with Fogo. I’m Fogolised 🔥",
  "This is not a phase. It’s my flame. I’m Fogolised 🔥",
  "I burn slow. I burn forever. I’m Fogolised 🔥",
  "You refresh pages. I refresh purpose. I’m Fogolised 🔥",
  "I mint my own legacy. I’m Fogolised 🔥",
  "I joined for the mission. Stayed for the fire. I’m Fogolised 🔥",
  "Fire never fakes. Neither do I. I’m Fogolised 🔥",
  "No alpha. Just flame. I’m Fogolised 🔥",
  "I spread fire. Not FOMO. I’m Fogolised 🔥",
  "Less airdrop, more airstrike. I’m Fogolised 🔥",
  "I didn’t just discover Fogo. I became it. I’m Fogolised 🔥",
  "Not hype-trained. Flame-trained. I’m Fogolised 🔥",
  "If loyalty was a chain — I’d be block 1. I’m Fogolised 🔥",
  "My identity is fireproof. I’m Fogolised 🔥",
  "I’m not just pledged. I’m Fogo-forged. I’m Fogolised 🔥",
  "I stoke the fire so others can feel the heat. I’m Fogolised 🔥",
  "I refresh not for perks — but for purpose. I’m Fogolised 🔥",
  "This isn't a feature. It's a firestorm. I’m Fogolised 🔥",
  "The pledge is simple: Forever Fogo. I’m Fogolised 🔥"
];

function generatePledge() {
  const random = pledges[Math.floor(Math.random() * pledges.length)];
  document.getElementById('pledgeBox').textContent = `${random} #FogoChain\n\nI’m Fogo’ised.`;
}

function copyToClipboard() {
  const pledgeText = document.getElementById('pledgeBox').textContent;
  navigator.clipboard.writeText(pledgeText).then(() => {
    alert('Copied! Paste it on your X post.');
  });
}

window.onload = generatePledge;
