const pledges = [
  "I stand with the flame. I’m Fogolised 🔥",
  "No hype, just heat. I’m Fogolised 🔥",
  "My wallet may be cold, but my soul’s on fire. I’m Fogolised 🔥",
  "This chain runs in my digital veins. I’m Fogolised 🔥",
  "I don’t follow trends. I follow the fire. I’m Fogolised 🔥",
  "Where there’s smoke, there’s me. I’m Fogolised 🔥",
  "My commitment is forged in flames. I’m Fogolised 🔥",
  "I walk with the ember of purpose. I’m Fogolised 🔥",
  "On-chain or off — I bring the heat. I’m Fogolised 🔥",
  "This is more than a chain. It's my ecosystem. I’m Fogolised 🔥",
  "Some stake, I pledge. I’m Fogolised 🔥",
  "Together, we light up the block. I’m Fogolised 🔥",
  "I’m not just a user. I’m a believer. I’m Fogolised 🔥",
  "Decentralized? Yes. Disconnected? Never. I’m Fogolised 🔥",
  "This fire’s not fading. I’m in for the long burn. I’m Fogolised 🔥",
  "No FUD, just flames. I’m Fogolised 🔥",
  "Not hype. It’s identity. I’m Fogolised 🔥",
  "I post, pledge, and power the chain. I’m Fogolised 🔥",
  "One fire. One future. One Fogo. I’m Fogolised 🔥",
  "I refresh my page, not my loyalty. I’m Fogolised 🔥",
  "In block we trust, in fire we unite. I’m Fogolised 🔥",
  "I don’t mint promises. I pledge them. I’m Fogolised 🔥",
  "Fueling the fire with every click. I’m Fogolised 🔥",
  "I run on passion. The chain runs on Fogo. I’m Fogolised 🔥",
  "It’s not just a chain. It’s where I belong. I’m Fogolised 🔥",
  "I carry the ember of change. I’m Fogolised 🔥",
  "I breathe decentralized fire. I’m Fogolised 🔥",
  "My loyalty is chain-locked. I’m Fogolised 🔥",
  "Pledged, not pressured. I’m Fogolised 🔥",
  "Fogo is not hype — it’s home. I’m Fogolised 🔥",
  "I don’t join chains. I become them. I’m Fogolised 🔥",
  "Every pledge adds fuel to the fire. I’m Fogolised 🔥",
  "I’m not early. I’m eternal. I’m Fogolised 🔥",
  "The flame chose me. I’m Fogolised 🔥",
  "No chill, just chain. I’m Fogolised 🔥",
  "My address is fire-encoded. I’m Fogolised 🔥",
  "Gasless or not — I stay lit. I’m Fogolised 🔥",
  "Chains don’t bind me, they empower me. I’m Fogolised 🔥",
  "I’m the block that burns the brightest. I’m Fogolised 🔥",
  "My role? Firestarter. I’m Fogolised 🔥",
  "I’m on fire, and it’s not metaphorical. I’m Fogolised 🔥",
  "This isn’t just a pledge. It’s a pact. I’m Fogolised 🔥",
  "Forged by fire, fueled by Fogo. I’m Fogolised 🔥",
  "No testnet, no problem. My loyalty is mainnet-ready. I’m Fogolised 🔥",
  "I don’t need incentives. I need ignition. I’m Fogolised 🔥",
  "If it’s not Fogo, it’s just smoke. I’m Fogolised 🔥",
  "This isn’t an airdrop. It’s a downpour of purpose. I’m Fogolised 🔥",
  "I don’t jump chains. I build them. I’m Fogolised 🔥",
  "With Fogo, I'm home. I’m Fogolised 🔥",
  "I don’t mint for clout. I mint for the cause. I’m Fogolised 🔥",
  "From embers to ecosystem — I grow with Fogo. I’m Fogolised 🔥",
  "Every keystroke is a spark. I’m Fogolised 🔥",
  "I don’t wait for flames. I make them. I’m Fogolised 🔥",
  "This chain is lit — and I’m the reason. I’m Fogolised 🔥",
  "You bring the code, I bring the fire. I’m Fogolised 🔥",
  "No faucet needed. I’m overflowing. I’m Fogolised 🔥",
  "I pledge not because I have to. But because I want to. I’m Fogolised 🔥",
  "Fogo isn't my project. It's my pulse. I’m Fogolised 🔥",
  "Not just Web3. Web🔥. I’m Fogolised 🔥",
  "This community? It’s lava. I’m Fogolised 🔥",
  "I pledged. I stayed. I burned. I’m Fogolised 🔥",
  "Every refresh brings a new flame. I’m Fogolised 🔥",
  "Code runs. I burn. I’m Fogolised 🔥",
  "Call me a pyro — I’m loyal to fire. I’m Fogolised 🔥",
  "Not an early adopter. An eternal one. I’m Fogolised 🔥",
  "This isn't onboarding. It’s ignition. I’m Fogolised 🔥",
  "I speak fluent Fogo. I’m Fogolised 🔥",
  "I vibe with validators. I’m Fogolised 🔥",
  "No roadmap needed when you follow fire. I’m Fogolised 🔥",
  "Proof of Flame. That's my consensus. I’m Fogolised 🔥",
  "I fuel this. Not just follow. I’m Fogolised 🔥",
  "I pledge with purpose, not pressure. I’m Fogolised 🔥",
  "Here since block zero. Staying till forever. I’m Fogolised 🔥",
  "You test tokens. I test loyalty. I’m Fogolised 🔥",
  "More than just gas fees — it's gas flames. I’m Fogolised 🔥",
  "I’m not bullish. I’m blazing. I’m Fogolised 🔥",
  "Proof of community, proof of commitment. I’m Fogolised 🔥",
  "Burned bridges. Built chains. I’m Fogolised 🔥",
  "No gimmicks. Just grit. I’m Fogolised 🔥",
  "I plant my flag in fire. I’m Fogolised 🔥",
  "This isn’t hype — it’s heritage. I’m Fogolised 🔥",
  "Community over coins. I’m Fogolised 🔥",
  "Let the doubters doubt. I burn bright. I’m Fogolised 🔥",
  "I’m not in for the drop. I’m in for the rise. I’m Fogolised 🔥",
  "Chain or no chain, I stand with Fogo. I’m Fogolised 🔥",
  "This is not a phase. It’s my flame. I’m Fogolised 🔥",
  "I burn slow. I burn forever. I’m Fogolised 🔥",
  "You refresh pages. I refresh purpose. I’m Fogolised 🔥",
  "I mint my own legacy. I’m Fogolised 🔥",
  "I joined for the mission. Stayed for the fire. I’m Fogolised 🔥",
  "Fire never fakes. Neither do I. I’m Fogolised 🔥",
  "No alpha. Just flame. I’m Fogolised 🔥",
  "I spread fire. Not FOMO. I’m Fogolised 🔥",
  "Less airdrop, more airstrike. I’m Fogolised 🔥",
  "I didn’t just discover Fogo. I became it. I’m Fogolised 🔥",
  "Not hype-trained. Flame-trained. I’m Fogolised 🔥",
  "If loyalty was a chain — I’d be block 1. I’m Fogolised 🔥",
  "My identity is fireproof. I’m Fogolised 🔥",
  "I’m not just pledged. I’m Fogo-forged. I’m Fogolised 🔥",
  "I stoke the fire so others can feel the heat. I’m Fogolised 🔥",
  "I refresh not for perks — but for purpose. I’m Fogolised 🔥",
  "This isn't a feature. It's a firestorm. I’m Fogolised 🔥",
  "The pledge is simple: Forever Fogo. I’m Fogolised 🔥"
  "I blaze my own trail. I'm Fogolised 🔥",
  "No fear, just fire. I'm Fogolised 🔥",
  "I trade truth, not hype. I'm Fogolised 🔥",
  "Crypto's future is Fogo. I'm Fogolised 🔥",
  "Decentralized is my default. I'm Fogolised 🔥",
  "I believe in burn and build. I'm Fogolised 🔥",
  "My power is permissionless. I'm Fogolised 🔥",
  "Rest is for the weak. I stay lit. I'm Fogolised 🔥",
  "I pledge to grow with Fogo. I'm Fogolised 🔥",
  "Contracts over conjecture. I'm Fogolised 🔥",
  "Transparency is my trade. I'm Fogolised 🔥",
  "I stake values, not tokens. I'm Fogolised 🔥",
  "Chain-first mindset. I'm Fogolised 🔥",
  "Purpose fuels my pledge. I'm Fogolised 🔥",
  "I build on conviction. I'm Fogolised 🔥",
  "My loyalty is algorithmic. I'm Fogolised 🔥",
  "No noise, just nodes. I'm Fogolised 🔥",
  "I’m here to improve the chain. I'm Fogolised 🔥",
  "Integrity beats incentives. I'm Fogolised 🔥",
  "I code, I pledge, I persist. I'm Fogolised 🔥",
  "Every block tells my story. I'm Fogolised 🔥",
  "I fight fog with fire. I'm Fogolised 🔥",
  "No cloak, just code. I'm Fogolised 🔥",
  "I breathe blockchain energy. I'm Fogolised 🔥",
  "Proof of flame, not hype. I'm Fogolised 🔥",
  "I spark innovation daily. I'm Fogolised 🔥",
  "My fuel is transparency. I'm Fogolised 🔥",
  "I pledge my purpose. I'm Fogolised 🔥",
  "I allow no FUD here. I'm Fogolised 🔥",
  "Commitment is my currency. I'm Fogolised 🔥",
  "Impact over image. I'm Fogolised 🔥",
  "I stand with receipts. I'm Fogolised 🔥",
  "No drama, just data. I'm Fogolised 🔥",
  "I write history onchain. I'm Fogolised 🔥",
  "I don’t follow trends. I forge them. I'm Fogolised 🔥",
  "I code the future. I'm Fogolised 🔥",
  "My block, my voice. I'm Fogolised 🔥",
  "I pledge for posterity. I'm Fogolised 🔥",
  "I align with utility. I'm Fogolised 🔥",
  "Community over content. I'm Fogolised 🔥",
  "Every transaction matters. I'm Fogolised 🔥",
  "I pledge to never relent. I'm Fogolised 🔥",
  "I champion decentralization. I'm Fogolised 🔥",
  "My trust is smart and auditable. I'm Fogolised 🔥",
  "Pushing boundaries, not hype. I'm Fogolised 🔥",
  "I pledge for lasting change. I'm Fogolised 🔥",
  "I stand on transparent ground. I'm Fogolised 🔥",
  "I code beyond borders. I'm Fogolised 🔥",
  "I’m in for the paradigm shift. I'm Fogolised 🔥",
  "No shortcuts to service. I'm Fogolised 🔥",
  "I pledge with purpose and poise. I'm Fogolised 🔥",
  "Code equals credibility. I'm Fogolised 🔥",
  "I advocate authenticity. I'm Fogolised 🔥",
  "I pledge my passion. I'm Fogolised 🔥",
  "I stand where data leads. I'm Fogolised 🔥",
  "No gatekeepers allowed. I'm Fogolised 🔥",
  "I define my own destiny. I'm Fogolised 🔥",
  "I rise with every validation. I'm Fogolised 🔥",
  "I claim ownership of change. I'm Fogolised 🔥",
  "I engage with substance. I'm Fogolised 🔥",
  "I pledge to stay foresighted. I'm Fogolised 🔥",
  "I elevate every block. I'm Fogolised 🔥",
  "I pledge to finite noise. I'm Fogolised 🔥",
  "I trade in trust and truth. I'm Fogolised 🔥",
  "I stand for sovereign sovereignty. I'm Fogolised 🔥",
  "I pledge with clarity and care. I'm Fogolised 🔥",
  "My loyalty outlasts cycles. I'm Fogolised 🔥",
  "I invest in fundamentals. I'm Fogolised 🔥",
  "I pledge for generational value. I'm Fogolised 🔥",
  "My code is my voice. I'm Fogolised 🔥",
  "I light flames of fairness. I'm Fogolised 🔥",
  "I believe in code that stands. I'm Fogolised 🔥",
  "I stand indexed by integrity. I'm Fogolised 🔥",
  "I bridge gaps with blocks. I'm Fogolised 🔥",
  "I embrace transparent tech. I'm Fogolised 🔥",
  "I pledge for equitable protocols. I'm Fogolised 🔥",
  "I trade conviction over volume. I'm Fogolised 🔥",
  "I resolve on resilience. I'm Fogolised 🔥",
  "I favor function over flash. I'm Fogolised 🔥",
  "I pledge in decentralization. I'm Fogolised 🔥",
  "I commit beyond consensus. I'm Fogolised 🔥",
  "I sparkle where data shines. I'm Fogolised 🔥",
  "I pledge with purpose, not performance. I'm Fogolised 🔥",
  "My flame is my foundation. I'm Fogolised 🔥",
  "I ignite community growth. I'm Fogolised 🔥",
  "I pledge to uphold openness. I'm Fogolised 🔥",
  "I rise above the noise. I'm Fogolised 🔥",
  "I champion trustless systems. I'm Fogolised 🔥",
  "I pledge to never cave. I'm Fogolised 🔥",
  "I forge ahead without fear. I'm Fogolised 🔥",
  "I build bridges, not barriers. I'm Fogolised 🔥",
  "I stand unwavering and unique. I'm Fogolised 🔥",
  "I march to the beat of blocks. I'm Fogolised 🔥",
  "I’m the spark of change. I'm Fogolised 🔥",
  "I keep the flame eternal. I'm Fogolised 🔥",
  "My pledge burns with purpose. I'm Fogolised 🔥"
];

function generatePledge() {
  const randomIndex = Math.floor(Math.random() * pledges.length);
  const pledge = pledges[randomIndex];
  const quotedPledge = `"${pledge}"`;

  // Update the UI
  document.getElementById("pledgeBox").innerText = quotedPledge;

  // Prepare tweet intent with quotes
  const tweetText = `Just took the pledge for FogoChain.\n\n${quotedPledge}\n\nTake yours now — before you're the last one left wondering.\n\n👉 https://fogo-pledge.vercel.app\n\n#PledgedToFogo`;
  const tweetIntentUrl = `https://x.com/intent/tweet?text=${encodeURIComponent(tweetText)}`;

  // Set the href for post button
  document.getElementById("postBtn").setAttribute("href", tweetIntentUrl);
}

// Run on page load
window.onload = generatePledge;

// Refresh pledge on button click
document.getElementById("refreshBtn").addEventListener("click", function (e) {
  e.preventDefault();
  generatePledge();
});
